import { StyleSheet } from 'react-native';

export const COLORS = {
  PRIMARY: '#7e57c2',
  SECONDARY: '#b39ddb',
  BACKGROUND: '#f9f4ff',
  TEXT_DARK: '#5e35b1',
  TEXT_LIGHT: '#9575cd',
};
export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#f9f4ff',
    marginTop: 50,
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#7e57c2',
    marginBottom: 10,
    fontFamily: 'sans-serif-light',
  },
  subtitle: {
    fontSize: 16,
    color: '#9575cd',
    textAlign: 'center',
  },
  inputContainer: {
    backgroundColor: 'white',
    borderRadius: 25,
    paddingHorizontal: 20,
    paddingVertical: 5,
    marginBottom: 20,
    shadowColor: '#7e57c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  input: {
    height: 50,
    color: '#5e35b1',
    fontSize: 16,
  },
  buttonGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
  },
  button: {
    backgroundColor: '#d1c4e9',
    padding: 15,
    borderRadius: 25,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
    shadowColor: '#7e57c2',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 2,
  },
  buttonActive: {
    backgroundColor: '#7e57c2',
    shadowColor: '#5e35b1',
  },
  buttonText: {
    color: '#5e35b1',
    fontWeight: '600',
  },
  buttonActiveText: {
    color: 'white',
  },
  searchButton: {
    backgroundColor: '#b39ddb',
    padding: 18,
    borderRadius: 25,
    alignItems: 'center',
    shadowColor: '#7e57c2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  searchButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
  },
  loadingText: {
    color: '#7e57c2',
    textAlign: 'center',
    marginTop: 20,
    fontSize: 16,
  },
  // Ajoutez à votre fichier styles.js
resultCardContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 15,
  marginTop: 30,
},
resultCard: {
  flex: 1,
  flexDirection: 'row',
  backgroundColor: 'white',
  borderRadius: 12,
  padding: 12,
  shadowColor: '#7e57c2',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 10,
  elevation: 3,
},
addToLibraryButton: {
  width: 40,
  height: 40,
  borderRadius: 20,
  backgroundColor: '#7e57c2',
  justifyContent: 'center',
  alignItems: 'center',
  marginLeft: 10,
  shadowColor: '#5e35b1',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.2,
  shadowRadius: 5,
  elevation: 3,
},
addToLibraryButtonText: {
  color: 'white',
  fontSize: 24,
  fontWeight: 'bold',
},
// Ajoutez à votre fichier styles.js
libraryButtonContainer: {
  alignItems: 'flex-end',
  marginBottom: 10,
},
libraryAccessButton: {
  backgroundColor: '#b39ddb',
  padding: 10,
  borderRadius: 15,
},
libraryAccessButtonText: {
  color: 'white',
  fontWeight: '600',
},
backButton: {
  backgroundColor: '#7e57c2',
  padding: 15,
  alignItems: 'center',
  position: 'absolute',
  bottom: 20,
  left: 20,
  right: 20,
  borderRadius: 25,
},
backButtonText: {
  color: 'white',
  fontWeight: 'bold',
  fontSize: 16,
},
});